baseURL = 'https://www.ad9cr.com/'
languageCode = 'en-us'
title = 'AD9CR Amateur Radio'
theme = 'ad9cr'

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Articles'
pageRef = '/articles'
weight = 15

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20

[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 30

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
